### ISSUE TITLE
Jupyter notebook log folder error

### ISSUE THREAD

**Issue by rupe120** [ARCC-RACE/deepracer-for-dummies#62]
I'm getting a permission denied error when I try to browse the Jupyter notebook log folder
    
    Server error: Traceback (most recent call last):
    File "/home/josh/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute result = await result
    File "/home/josh/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper yielded = next(result)
    File "/home/josh/anaconda3/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 112, in get path=path, type=type, format=format, content=content,
    File "/home/josh/anaconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 431, in get model = self._dir_model(path, content=content)
    File "/home/josh/anaconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model if self.should_list(name) and not is_file_hidden(os_path, stat_res=st):
    File "/home/josh/anaconda3/lib/python3.7/site-packages/notebook/utils.py", line 164, in is_file_hidden_posix stat_res = os.stat(abs_path) PermissionError: [Errno 13] Permission denied: '/home/josh/Dev/github/ARCC-RACE/deepracer-for-dummies/aws-deepracer-workshops/log-analysis/logs/latest'

The folder

    aws-deepracer-workshops/log-analysis/log

Links to the folder

    docker/volumes/robo/checkpoint/log/latest

Links to the folder

    /root/.ros/log/

I believe that the link to `/root/.ros/log/` is the problem. Is this maybe from installing something as sudo? I feel like this should reference a folder in my user folders, yes?

**Comment by rupe120** [comment]
when I searched for the .ros folder on my system it came up in the docker content. Is this symlink only intended for use inside the docker container?

**Comment by rupe120** [comment]
I'm mainly trying to determine what set for a `stream_name` in the `Training_analysis` notebook. Is the log folder that I'm experiencing the error with, the same log folder in the `fname` variable where `stream_name` is used?
